// This file is generated by scripts/generate_mock_data_from_db.py.
// Edit the SQLite DB and regenerate instead of editing clinic data by hand.

export const clinics = [
  {
    id: "7",
    slug: "cnp-apgujeong",
    name: "CNP Dermatology Apgujeong",
    location: "강남구",
    categories: ["Clinic Guide"],
    languages: ["EN"],
    priceRange: "Price range listed after clinic confirmation",
    sponsored: false,
    description: "Clinic profile draft created from Kakao Local API candidate. Needs manual review before publishing.",
    foreignerSupport: "Language support not yet verified",
    beforeChecklist: ["Bring your passport", "Confirm appointment time before visiting", "Prepare allergy and medication information"],
    aftercareNotes: "Follow the clinic's aftercare instructions and contact the clinic if symptoms feel unusual.",
  },
  {
    id: "10",
    slug: "comfort-plastic-surgery",
    name: "Comfort Plastic Surgery Gangnam",
    location: "강남구",
    categories: ["Clinic Guide"],
    languages: ["EN"],
    priceRange: "Price range listed after clinic confirmation",
    sponsored: false,
    description: "Clinic profile draft created from Kakao Local API candidate. Needs manual review before publishing.",
    foreignerSupport: "Language support not yet verified",
    beforeChecklist: ["Bring your passport", "Confirm appointment time before visiting", "Prepare allergy and medication information"],
    aftercareNotes: "Follow the clinic's aftercare instructions and contact the clinic if symptoms feel unusual.",
  },
  {
    id: "8",
    slug: "diod-cheongdam",
    name: "DIOD Dermatology Cheongdam",
    location: "강남구",
    categories: ["Clinic Guide"],
    languages: ["EN"],
    priceRange: "Price range listed after clinic confirmation",
    sponsored: false,
    description: "Clinic profile draft created from Kakao Local API candidate. Needs manual review before publishing.",
    foreignerSupport: "Language support not yet verified",
    beforeChecklist: ["Bring your passport", "Confirm appointment time before visiting", "Prepare allergy and medication information"],
    aftercareNotes: "Follow the clinic's aftercare instructions and contact the clinic if symptoms feel unusual.",
  },
  {
    id: "9",
    slug: "thehill-sinsa",
    name: "The Hill Dermatology Sinsa",
    location: "강남구",
    categories: ["Clinic Guide"],
    languages: ["EN"],
    priceRange: "Price range listed after clinic confirmation",
    sponsored: false,
    description: "Clinic profile draft created from Kakao Local API candidate. Needs manual review before publishing.",
    foreignerSupport: "Language support not yet verified",
    beforeChecklist: ["Bring your passport", "Confirm appointment time before visiting", "Prepare allergy and medication information"],
    aftercareNotes: "Follow the clinic's aftercare instructions and contact the clinic if symptoms feel unusual.",
  },
];

export const phrasebook = {
  reception: [
    { kr: "예약이 있어요", en: "I have an appointment", romanized: "Yeyagi isseoyo" },
    { kr: "영어 가능한 직원 있나요?", en: "Is there an English-speaking staff?", romanized: "Yeongeo ganeunghan jikwon innayo?" },
    { kr: "처음 방문입니다", en: "This is my first visit", romanized: "Cheoeum bangmunimnida" },
  ],
  payment: [
    { kr: "카드로 결제할 수 있나요?", en: "Can I pay by card?", romanized: "Kadeu-ro gyeoljehal su innayo?" },
    { kr: "영수증 주세요", en: "Please give me a receipt", romanized: "Yeongsujeung juseyo" },
    { kr: "세금 환급 가능한가요?", en: "Is tax refund possible?", romanized: "Segeum hwanggeup ganeunghangayo?" },
  ],
  medical: [
    { kr: "알레르기가 있어요", en: "I have an allergy", romanized: "Allereugi isseoyo" },
    { kr: "약을 먹고 있어요", en: "I'm taking medication", romanized: "Yageul meokgo isseoyo" },
    { kr: "여기가 아파요", en: "It hurts here", romanized: "Yeogi apayo" },
  ],
};

export const taxiCards = [
  {
    clinicName: clinics[0]?.name ?? "Clinic",
    address: "서울 강남구 압구정로 123",
    addressEn: "123 Apgujeong-ro, Gangnam-gu, Seoul",
    note: "지하철 3호선 압구정역 2번 출구에서 도보 5분",
    noteEn: "5 min walk from Exit 2, Apgujeong Station (Line 3)",
  },
];

export const aftercareChecklists = {
  skinBooster: [
    { day: "Day 1", tasks: ["Keep area clean and dry", "Avoid touching treated area", "Use gentle cleanser only"] },
    { day: "Day 2–3", tasks: ["Apply prescribed cream if given", "SPF50+ sunscreen mandatory", "Swelling is normal"] },
    { day: "Day 4–7", tasks: ["Resume normal skincare slowly", "Avoid exfoliants", "Take progress photos"] },
    { day: "Day 7+", tasks: ["Full skincare routine OK", "Book follow-up if needed", "Share results with clinic"] },
  ],
};
