#!/usr/bin/env python3
"""
Generate src/lib/mock-data.ts from the reviewed clinics table.

Usage:
  python3 scripts/generate_mock_data_from_db.py

This keeps the app static/demo-friendly while allowing clinic data to be
managed in SQLite first.
"""

from __future__ import annotations

import json
import sqlite3
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DB_PATH = ROOT / "data" / "kclinic.db"
OUTPUT_PATH = ROOT / "src" / "lib" / "mock-data.ts"


def js_string(value: str | None) -> str:
    return json.dumps(value or "", ensure_ascii=False)


def js_array(values: list[str]) -> str:
    return json.dumps(values, ensure_ascii=False)


def fetch_clinics(conn: sqlite3.Connection) -> list[dict]:
    conn.row_factory = sqlite3.Row
    rows = conn.execute(
        """
        SELECT *
        FROM clinics
        WHERE profile_status = 'published'
        ORDER BY
          CASE sponsored_status WHEN 'sponsored' THEN 0 ELSE 1 END,
          display_name
        """
    ).fetchall()

    clinics = []
    for row in rows:
        clinic_id = row["id"]
        languages = [
            item["language_code"]
            for item in conn.execute(
                "SELECT language_code FROM clinic_languages WHERE clinic_id = ? ORDER BY language_code",
                (clinic_id,),
            ).fetchall()
        ]
        categories = [
            item["category"]
            for item in conn.execute(
                "SELECT category FROM clinic_categories WHERE clinic_id = ? ORDER BY category",
                (clinic_id,),
            ).fetchall()
        ]

        before_notes = row["before_visit_notes"] or ""
        before_checklist = [
            item.strip()
            for item in before_notes.replace("\n", ". ").split(".")
            if item.strip()
        ]
        if not before_checklist:
            before_checklist = [
                "Bring your passport",
                "Confirm appointment time before visiting",
                "Prepare allergy and medication information",
            ]

        clinics.append(
            {
                "id": str(row["id"]),
                "slug": row["slug"],
                "name": row["display_name"],
                "location": row["location_label"] or row["district"] or "Seoul",
                "categories": categories or ["Clinic Guide"],
                "languages": languages or ["EN"],
                "priceRange": row["price_range_label"] or "Price range listed after clinic confirmation",
                "sponsored": row["sponsored_status"] == "sponsored",
                "description": row["description"] or "Reviewed clinic guide for international medical travelers.",
                "foreignerSupport": row["foreigner_support"] or "Language support not yet verified",
                "beforeChecklist": before_checklist,
                "aftercareNotes": row["aftercare_notes"] or "Follow the clinic's aftercare instructions and contact the clinic if symptoms feel unusual.",
            }
        )

    return clinics


def render_clinics(clinics: list[dict]) -> str:
    blocks = []
    for clinic in clinics:
        blocks.append(
            "\n".join(
                [
                    "  {",
                    f"    id: {js_string(clinic['id'])},",
                    f"    slug: {js_string(clinic['slug'])},",
                    f"    name: {js_string(clinic['name'])},",
                    f"    location: {js_string(clinic['location'])},",
                    f"    categories: {js_array(clinic['categories'])},",
                    f"    languages: {js_array(clinic['languages'])},",
                    f"    priceRange: {js_string(clinic['priceRange'])},",
                    f"    sponsored: {str(clinic['sponsored']).lower()},",
                    f"    description: {js_string(clinic['description'])},",
                    f"    foreignerSupport: {js_string(clinic['foreignerSupport'])},",
                    f"    beforeChecklist: {js_array(clinic['beforeChecklist'])},",
                    f"    aftercareNotes: {js_string(clinic['aftercareNotes'])},",
                    "  },",
                ]
            )
        )
    return "\n".join(blocks)


def render_file(clinics: list[dict]) -> str:
    return f"""// This file is generated by scripts/generate_mock_data_from_db.py.
// Edit the SQLite DB and regenerate instead of editing clinic data by hand.

export const clinics = [
{render_clinics(clinics)}
];

export const phrasebook = {{
  reception: [
    {{ kr: "예약이 있어요", en: "I have an appointment", romanized: "Yeyagi isseoyo" }},
    {{ kr: "영어 가능한 직원 있나요?", en: "Is there an English-speaking staff?", romanized: "Yeongeo ganeunghan jikwon innayo?" }},
    {{ kr: "처음 방문입니다", en: "This is my first visit", romanized: "Cheoeum bangmunimnida" }},
  ],
  payment: [
    {{ kr: "카드로 결제할 수 있나요?", en: "Can I pay by card?", romanized: "Kadeu-ro gyeoljehal su innayo?" }},
    {{ kr: "영수증 주세요", en: "Please give me a receipt", romanized: "Yeongsujeung juseyo" }},
    {{ kr: "세금 환급 가능한가요?", en: "Is tax refund possible?", romanized: "Segeum hwanggeup ganeunghangayo?" }},
  ],
  medical: [
    {{ kr: "알레르기가 있어요", en: "I have an allergy", romanized: "Allereugi isseoyo" }},
    {{ kr: "약을 먹고 있어요", en: "I'm taking medication", romanized: "Yageul meokgo isseoyo" }},
    {{ kr: "여기가 아파요", en: "It hurts here", romanized: "Yeogi apayo" }},
  ],
}};

export const taxiCards = [
  {{
    clinicName: clinics[0]?.name ?? "Clinic",
    address: "서울 강남구 압구정로 123",
    addressEn: "123 Apgujeong-ro, Gangnam-gu, Seoul",
    note: "지하철 3호선 압구정역 2번 출구에서 도보 5분",
    noteEn: "5 min walk from Exit 2, Apgujeong Station (Line 3)",
  }},
];

export const aftercareChecklists = {{
  skinBooster: [
    {{ day: "Day 1", tasks: ["Keep area clean and dry", "Avoid touching treated area", "Use gentle cleanser only"] }},
    {{ day: "Day 2–3", tasks: ["Apply prescribed cream if given", "SPF50+ sunscreen mandatory", "Swelling is normal"] }},
    {{ day: "Day 4–7", tasks: ["Resume normal skincare slowly", "Avoid exfoliants", "Take progress photos"] }},
    {{ day: "Day 7+", tasks: ["Full skincare routine OK", "Book follow-up if needed", "Share results with clinic"] }},
  ],
}};
"""


def main() -> int:
    if not DB_PATH.exists():
        raise SystemExit(f"Missing DB: {DB_PATH}. Run scripts/init_clinic_db.py first.")

    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    clinics = fetch_clinics(conn)
    if not clinics:
        raise SystemExit("No published clinics found.")

    OUTPUT_PATH.write_text(render_file(clinics), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH}")
    print(f"Clinics exported: {len(clinics)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

